version: '3.7'

services:
    dynamodb:
        container_name: dynamodb
        image: amazon/dynamodb-local:latest
        entrypoint: java
        command: "-jar DynamoDBLocal.jar -sharedDb"
        restart: always
        volumes:
          - dynamodb-data:/data
        ports:
          - "4566:8000"
 
volumes:
    dynamodb-data: